### ISSUE TITLE
Add option to create new releases as drafts

### ISSUE THREAD

**Issue by thomasf** [drone-plugins/drone-github-release#10]

**Comment by thomasf** [comment]
Question: Can I implement #8, #9 and #10 as one pull request?

If the code is expanded without modification the build/get/new/upload-functions will get even more arguments. Should I create a struct which holds common data like owner/repo and stuff from vargs for my the new features?

**Comment by tboerger** [comment]
#8 seems to be useless but the others can be done in a single pr with different commits

**Comment by tboerger** [comment]
But keep in mind to stay backwards compatible
