### ISSUE TITLE
Failed to create the release: 404 Discussions are not enabled on this repository

### ISSUE THREAD

**Issue by bravier** [drone-plugins/drone-github-release#113]
**Context**

Today when creating a release I got the following error:
```
Release vx.y.z will be created and published
Not creating a discussion
time="2022-05-12T11:02:18Z" level=error msg="execution failed: failed to create the release: failed to create or edit a release: failed to create release: POST https://api.github.com/repos/:owner/:repo/releases: 404 Discussions are not enabled on this repository. []"
```

**Explanation**

It looks like **#89 introduced a new breaking change**: it sends in the the request to Github the parameter `discussion_category_name` everytime, even if you don't want to use this feature (it seems to send an empty string).

The problem is that many people do not have discussions enabled on their repo and when you call the Github API with an empty string for this parameter you'll get:
```bash
curl \
  -X POST \
  -H "Accept: application/vnd.github.v3+json" \
  https://api.github.com/repos/:owner/:repo/releases \
  -d '{"tag_name":"v1.0.0", "discussion_category_name":""}'
```
```json
{
  "message": "Discussions are not enabled on this repository.",
  "documentation_url": "https://docs.github.com/rest/reference/repos#create-a-release"
}
```

**Possible solution**

A solution would be to not send the parameter at all if you don't use discussions (instead of an empty string).

**Useful links**

Github Documentation about [_Create a release_](https://docs.github.com/en/rest/releases/releases#create-a-release) API endpoint.

**Comment by donny-dont** [comment]
Reverted in https://github.com/drone-plugins/drone-github-release/pull/114 can you verify everything is working for you now @bravier ?

**Comment by bravier** [comment]
Thanks for the quick response @donny-dont!
Just retested and everything is fine on my side.
One last thing, can you tag the new image containing the revert as `latest` on Docker Hub please?
![image](https://user-images.githubusercontent.com/3956758/168098008-633557d7-a4e1-4d24-8f65-63ce4ccf47d4.png)

**Comment by donny-dont** [comment]
Ugh sorry looks like the Windows builds failed...

**Comment by bravier** [comment]
No issues :)
This issue is now resolved so I'll close it.
