### ISSUE TITLE
add prerelease flag

### ISSUE THREAD

**Issue by firecyberice** [drone-plugins/drone-github-release#14]
Adding a flag for github prereleases would be nice so you can e.g. publish a build from a "testing" branch as prerelease.

**Comment by tboerger** [comment]
A testing branch can anyway not get used, you can only release tags on github, no branches

**Comment by firecyberice** [comment]
@tboerger Yes but you can tag in any branch like `vX.Y.Z-rc1` and if the branch is testing you can use prerelease to push.

**Comment by firecyberice** [comment]
I just looked at https://github.com/drone-plugins/drone-github-release/blob/master/DOCS.md
There is already a `draft` flag.

**Comment by tboerger** [comment]
> I just looked at https://github.com/drone-plugins/drone-github-release/blob/master/DOCS.md
> There is already a draft flag.

Draft is still something different than the prerelease.
