### ISSUE TITLE
generate pull request

### ISSUE THREAD

**Issue by ccwillia** [drone-plugins/drone-github-release#22]
Is it possible to open a pull request with this plugin.  We use branches instead of releases and it would be awesome to open a pull request as part of my pipeline

**Comment by tuxity** [comment]
It's a good idea, I never thought of that. But I think it could be another plugin, not in this one.

**Comment by tboerger** [comment]
This won't happen for this plugin, it's using github releases, and github releases only work for tags. But feel free to create another plugin that solves your use case.
