### ISSUE TITLE
Add to plugin registry

### ISSUE THREAD

**Issue by bradrydzewski** [drone-plugins/drone-github-release#25]
Add to the plugin registry and document the required scopes for the personal access token. For example `public_repo` for public repos and `repo` for private repos?

**Comment by tboerger** [comment]
Sounds like a good plan :)

**Comment by xoxys** [comment]
@tboerger same here? :)

**Comment by tboerger** [comment]
Not entirely, the token scopes have not been documented at all.

**Comment by xoxys** [comment]
This means documenting the GitHub settings for your access token described here: https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/ ?

**Comment by tboerger** [comment]
Yeah something like that if you need a scope for private or public repos.

**Comment by xoxys** [comment]
Ok I can do this

**Comment by tboerger** [comment]
Thanks @xoxys
