### ISSUE TITLE
Github Semver tag autoincrement

### ISSUE THREAD

**Issue by jaisonpjohn** [drone-plugins/drone-github-release#27]
In our team, we had a requirement to auto increment the semver tag on each master push, we were using netflix's Nebula Release Plugin for that purpose(Since we are a JavaShop). This will work only for Java language, so we came up with a generic solution https://github.com/jaisonpjohn/github-tag-autoincrement so that it can be included as a step in drone pipeline for any programming language's build. Can this functionality be included in the drone core or in this plugin instead? If we include this functionality in drone core, we may not need to ask the repo information and credential again, we already have user's repo information as well as the authtoken.

**Comment by tboerger** [comment]
The core plugins are kept pretty simple intentional, they should do a single task and this task should be done well. So IMHO this should stay as a standalone plugin. But those are just my 2 cents

**Comment by tboerger** [comment]
This doesn't match for this plugin, this plugin only gets used if a Git tag had been created.
