### ISSUE TITLE
unclear if "files" needs to be list or not

### ISSUE THREAD

**Issue by yosefy** [drone-plugins/drone-github-release#36]
github_release:
    image: plugins/github-release
    secrets: [ github_token ]
    files:
      - test
(doesn't upload )

github_release:
    image: plugins/github-release
    secrets: [ github_token ]
    files: test
(works good)

better stick with single format (list)

**Comment by tboerger** [comment]
Both formats are working totally fine and this is the expect behavior.

**Comment by yosefy** [comment]
i have tested again and no idea what went wrong before but now is ok
thanks
