### ISSUE TITLE
plugin should fail if files are not found

### ISSUE THREAD

**Issue by jesusch** [drone-plugins/drone-github-release#39]
currently the plugin does not care if it finds the specified files or not. if the pattern does not exists it simply creates an empty release
From my POV it should fail in that case

**Comment by tboerger** [comment]
That totally depends on the view, I'm personally totally fine that it doesn't fail. Maybe we can add a flag that defines "fail on missing", but since the files are just a glob pattern it's hard to define when some pattern really failed.

**Comment by jesusch** [comment]
fail_on_missing would be a good compromise not to break old installations
in that case a glob pattern could be checked if at least one file is affected
for files that does not contain globs it should fail

**Comment by jesusch** [comment]
If no glob is specified we continue to create a blank release, and assume that is intentional <- Maybe I'm wrong, but for me a glob is something with a wildcard (*?[a-z])
If there is a new config value (fail_on_missing) I'd suggest (sorry I have no clue about go)
```
for f in files
  if f contains_glob
    if 0 != $(ls $f|count)
      return err
  else
    if ! is_file($f)
      return err
```

**Comment by bradrydzewski** [comment]
`len(p.Config.Files)` means that `files: ` is not configured in the yaml (aka no glob pattern is specified). If a user does not specify `files` then we assume the user wants to tag a release but does not need to upload any files. 

I recommend reading through the code, which will give you a better understanding of how my proposed logic would work.

**Comment by voltagex** [comment]
Just my two cents:

* the plugin shouldn't fail/succeed silently when no files are uploaded

* there needs to be a bit better documentation - 
  * What path are the files relative to? (pwd, it turns out)
  * How should releases be created? (tar -cf in another job, but is there a better way?)
