### ISSUE TITLE
Files are not being uploaded to GitHub Releases

### ISSUE THREAD

**Issue by sr229** [drone-plugins/drone-github-release#60]
This could be related to #39 since it doesn't tell much if it did really fail to see files.

We used this plugin to try releasing files but none of the files we added in is uploaded.

![image](https://user-images.githubusercontent.com/14976516/72082810-bae6db00-333b-11ea-90dc-5fb66b7a7035.png)

It just adds a empty release, nothing more.

**Comment by tboerger** [comment]
This indicates that your files list doesn't match any file, so obviously it's not uploading anything.

**Comment by sr229** [comment]
I think we figured out what's wrong, looks like our build dir is nested again in the subdirectoy hence github-releases can't detect it. Resolving this.
