### ISSUE TITLE
Add option to fail if ref/tag does not exist

### ISSUE THREAD

**Issue by thomasf** [drone-plugins/drone-github-release#8]

**Comment by thomasf** [comment]
I guess this behavior is  already implied but not checked because of these lines:

```go

if build.Event != "tag" {
		fmt.Printf("The GitHub Release plugin is only available for tags\n")
		os.Exit(0)
	}
```

**Comment by tboerger** [comment]
This doesn't make sense as its working anyway only for tag events, so this tag must already exist

**Comment by thomasf** [comment]
Drone exec allows for -event "tag" which by default creates a telease called like the current branch iirc.

**Comment by thomasf** [comment]
There are probably other cases as wel even though l dont have time to figure them out. Proper input validation isnt a bad thing anyway.

**Comment by thomasf** [comment]
Compared to the other two issues I opened this is a non issue though. The other ones I feel are important. I'll get to fixing those first.

**Comment by tboerger** [comment]
I think this issue is just bad configuration :)
The others are real improvements
